### ISSUE TITLE
Hot Key to clear zones

### ISSUE THREAD

**Issue by CricketBr** [ClaudeMetz/AssemblyAnalyst#6]
I really like the new /aa-clear-zones console command.

- It should be on the front page, as a feature, not just buried in the change log.

- A hot key and/or hot bar entry would make it even better.

Thanks for an extremely useful mod. I play SeaBlock, and use a lot of beacons. This mod really helps me find the bottlenecks.

**Comment by martinvonwittich** [comment]
I keep forgetting the command and always have to scroll through my command history to find it, so some easier way would be appreciated. Doesn't have to be a hotkey for me, I think a button on the Legend would already do the trick and be probably more intuitive for most people?

**Comment by ClaudeMetz** [comment]
Appreciate the suggestion, I implemented a keyboard shortcut for the next release.

A button in the UI is a bit awkward, since the UI only shows with the selection tool in hand, so clicking a button while holding that is weird.
